name: "Platform Image Test"

on:
  pull_request:
    branches:
      - master
    types: [labeled]
  schedule:
    - cron: '0 6 * * *'

jobs:
  Platform-Image-Test:
    if: github.repository == 'argoproj/argo-cd'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: test-arm64-image
        run: |
          IMAGE_PLATFORMS=linux/arm64
          sed s/'--platform=$BUILDPLATFORM '/''/g Dockerfile |  \
          docker buildx build --platform $IMAGE_PLATFORMS -f - --push=false .
        if: contains(github.event.pull_request.labels.*.name, 'test-arm64-image') || github.event_name == 'schedule'